### ISSUE TITLE
Scanning with iPhone

### ISSUE THREAD

**Issue by Mike-LilRegie** [lilregie/scanning-app#4] opened 2022-03-14 00:31 UTC
It asks to select camera, with options for "front camera" and "back camera".

Even if I choose "back camera" no camera seems to be used. If I choose "front camera" the camera appears to be working, but it won't scan anything.

I'm not sure if I'm doing something wrong, or if it should be working, or if there's a bug.

Using iPhone Xs and software version 15.3.1

![IMG_4131](https://user-images.githubusercontent.com/254926/158086427-f20684ae-4f6c-4a1e-9d9d-c131c256bcef.PNG)

**Comment by Fallstop** [comment] 2022-03-14 22:20
Looking at the problems, here are my guesses to the two root causes:
 - Back Camera not loading: Something weird going on with the media constraints on IOS?
 - Not Scanning: Probably the web worker isn't loading, could be something to do with the CSP or Vite loading it weirdly.

Unfortunately, I don't have any IOS devices easily accessible to debug with, so if you could get some data for me that would be great!
 - Narrow problem space by testing what happens with the just the scanner part [here](https://jsqr.modern-svelte-qr-scanner.pages.dev/). Note what the barcode engine is when testing.
 - If that page doesn't work, could you get the [debug output](https://www.lifewire.com/activate-the-debug-console-in-safari-445798), just send a screenshot of the console. Hopefully there will be some clear errors in the console.

**Comment by Mike-LilRegie** [comment] 2022-03-14 23:03
Ok, so when I go to that page:

- if I choose Back camera first, no camera working
- if I choose Front camera first, or after Back camera, it works
- if I choose Back camera after having chosen Front camera, it works as the Front camera. Even though Back camera is still selected.

The barcode engine is: jsqr

**Comment by Mike-LilRegie** [comment] 2022-03-14 23:11
It did, on front camera, show this after scanning a vaccine pass. That's good?
![IMG_4132](https://user-images.githubusercontent.com/254926/158275519-913e120f-b479-45be-8f55-56f23ab58f17.PNG)

**Comment by Fallstop** [comment] 2022-03-15 03:24
Okay cool, so that narrows it down.
 - Back Camera not loading: Something weird going on with the media constraints on IOS?
    - Could you send screenshots of devtools output after trying to switch to the back camera on the [scanner page](https://jsqr.modern-svelte-qr-scanner.pages.dev/)?
 - Not Scanning: Probably the web worker isn't loading, something to do with the CSP policies.
    - Could you send screenshots of devtools output of the [check-in tool in staging](https://checkin.lilregiestaging.com/checkin/events)?

> show this after scanning a vaccine pass. That's good?

Just narrows down the cause, it means that's not some obscure problem with the scanner, but an obscure problem with the security polices, which might require them to be opened up further.

**Comment by Mike-LilRegie** [comment] 2022-03-16 20:43
<img width="1271" alt="Screen Shot 2022-03-17 at 9 40 50 AM" src="https://user-images.githubusercontent.com/254926/158687262-4daab405-802c-45f4-bc2a-80dfbc6ebbbb.png">

Screenshot when trying to access Back camera

**Comment by Mike-LilRegie** [comment] 2022-03-16 20:50
I can scan a vaccine pass with iPhone, but only via front camera. It would certainly be easier to use the back camera for the scanning.

**Comment by Fallstop** [comment] 2022-03-16 22:22
Fixed by changing the media restraints from Instascan's legacy format to the newer standard.

Safari just ignored the legacy format, the key part of which being the chosen device ID, meaning it always selected the front camera instead of the camera chosen in the dialog box.

**Closed as completed by Fallstop** 2022-03-16 22:22 UTC
